<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">

<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
	<html>
		<head>
			<title>XML Sitemap</title>
			<style type="text/css">
				body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif; color: #444; }
				#sitemap { max-width: 960px; margin: 2rem auto; }
				#sitemap h1 { font-size: 2em; }
				#sitemap table { width: 100%; border-collapse: collapse; }
				#sitemap th, #sitemap td { padding: 0.75rem; border-bottom: 1px solid #eee; }
				#sitemap th { text-align: left; font-weight: bold; }
				#sitemap a { color: #1a0dab; text-decoration: none; }
				#sitemap a:hover { text-decoration: underline; }
				#sitemap footer { margin-top: 2rem; font-size: 0.9em; color: #777; }
			</style>
		</head>
		<body>
			<div id="sitemap">
				<h1>XML Sitemap</h1>
				<p>This is an XML sitemap generated by the SEO 44 plugin, intended for consumption by search engines.</p>
				<xsl:if test="sitemap:sitemapindex">
					<p>This is a sitemap index file that contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.</p>
				</xsl:if>
				<xsl:if test="sitemap:urlset">
					<p>This sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
				</xsl:if>
				<table>
					<thead>
						<tr>
							<th>URL</th>
							<xsl:if test="//sitemap:lastmod"><th>Last Modified</th></xsl:if>
						</tr>
					</thead>
					<tbody>
						<xsl:apply-templates />
					</tbody>
				</table>
				<footer>Generated by SEO 44.</footer>
			</div>
		</body>
	</html>
</xsl:template>

<xsl:template match="sitemap:sitemapindex/sitemap:sitemap">
	<tr>
		<td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
		<xsl:if test="sitemap:lastmod">
			<td><xsl:value-of select="sitemap:lastmod"/></td>
		</xsl:if>
	</tr>
</xsl:template>

<xsl:template match="sitemap:urlset/sitemap:url">
	<tr>
		<td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
		<xsl:if test="sitemap:lastmod">
			<td><xsl:value-of select="sitemap:lastmod"/></td>
		</xsl:if>
	</tr>
</xsl:template>

</xsl:stylesheet>